// ml/relevance/features.rs — feature extraction for the relevance gate
// (PLAN-ML-GATES §6).
//
// One feature vector per CANDIDATE (a file, memory, or search result the
// retriever could pull into context) scored against the current task and
// the rest of the candidate set. The load-bearing signal is "does this
// deserve the tokens" — BM25 over the candidate set is the strong
// classical baseline (§6: the biggest accuracy win available given the
// bundled embedder is only hashed char-trigram TF-IDF); the semantic
// cosine, duplication, shape, and task×content interaction channels let
// the net correct the cases where lexical overlap alone is wrong
// (synonym matches, wrong-topic traps, task-dependent labels — §9).
// Deterministic: scalar f32, fixed order, injected context.

use std::collections::HashMap;
use std::sync::LazyLock;

use crate::ml::freshness::features::cosine;
use crate::rt::ai::sofuu_tfidf_embed;

pub const RELEVANCE_FEATURES: usize = 37;
const EMBED_DIM: usize = 768;

/// BM25 parameters — the standard retrieval defaults. Deterministic
/// constants, shared by training and serving (same code path).
const BM25_K1: f32 = 1.5;
const BM25_B: f32 = 0.75;

/// What kind of thing a candidate is. Drives the one-hot channel and the
/// brain strength/role features (memories only).
#[derive(Clone, Copy, Debug, PartialEq)]
pub enum CandKind {
    File,
    Memory,
    Web,
    Other,
}

impl CandKind {
    fn one_hots(self) -> [f32; 4] {
        match self {
            CandKind::File => [1.0, 0.0, 0.0, 0.0],
            CandKind::Memory => [0.0, 1.0, 0.0, 0.0],
            CandKind::Web => [0.0, 0.0, 1.0, 0.0],
            CandKind::Other => [0.0, 0.0, 0.0, 1.0],
        }
    }
}

#[derive(Clone, Copy, Debug)]
pub struct CandidateInput<'a> {
    pub text: &'a str,
    pub kind: CandKind,
    /// Brain memory strength in [0,1]; 0 for non-memories.
    pub strength: f32,
    /// Brain memory role id (0 = none / non-memory). Encoded as a scalar.
    pub role: u8,
    /// Source path when the candidate is a file ("" otherwise) — feeds the
    /// path/extension channels.
    pub path: &'a str,
}

/// Everything a candidate is scored against. `candidates` is the full menu
/// the retriever chose from (BM25's document collection); `kept` lists the
/// indices already accepted into context (near-duplicate detection);
/// `recent` is the recent visible history text (already-visible channel).
pub struct RelevanceContext<'a> {
    pub task: &'a str,
    pub recent: &'a str,
    pub candidates: &'a [CandidateInput<'a>],
    pub kept: &'a [usize],
}

/* ── Anchors ─────────────────────────────────────────────────────── */

const BOILERPLATE_ANCHOR: &str = "permission is hereby granted free of charge to any \
    person obtaining a copy of this software the software is provided as is without \
    warranty of any kind express or implied copyright notice license terms of service \
    all rights reserved redistribution and use in source and binary forms";

/// Generated / lockfile / minified markers — the "never useful" class (§9).
const NEVER_USE_WORDS: &[&str] = &[
    "generated by", "do not edit", "auto-generated", "code generated", "machine generated",
    "lockfile", "package-lock", "cargo.lock", "this file is generated", "checksum",
];

/// Version/changelog markers — the class that is useful ONLY when the task
/// is about versions (§9 "a changelog entry → use when the task is about
/// versions, not otherwise").
const VERSION_WORDS: &[&str] = &[
    "changelog", "release notes", "version", "breaking change", "deprecated",
    "upgrade", "migration guide", "semver", "tagged",
];

/// Task phrasings that ask about versions/time.
const VERSION_TASK_WORDS: &[&str] = &[
    "version", "upgrade", "changelog", "release", "latest", "deprecated", "migrate",
];

/// Task phrasings that ask about behaviour (tests become useful — §9).
const BEHAVIOUR_TASK_WORDS: &[&str] = &[
    "behaviour", "behavior", "how does", "what does", "test", "expect", "should",
    "why does", "does it", "work correctly",
];

/// Test-file markers — the candidate class whose label flips with the task.
const TEST_CONTENT_WORDS: &[&str] = &[
    "#[test]", "assert", "it should", "describe(", "test(", "expect(", "spec",
    "test case", "unit test",
];

static BOILERPLATE_VEC: LazyLock<Vec<f32>> = LazyLock::new(|| embed_text(BOILERPLATE_ANCHOR));

fn embed_text(text: &str) -> Vec<f32> {
    let mut v = vec![0.0f32; EMBED_DIM];
    sofuu_tfidf_embed(text.as_bytes(), &mut v, EMBED_DIM);
    v
}

/* ── Lexical helpers ─────────────────────────────────────────────── */

/// Lowercase word tokens (alphanumeric runs, `_` kept for symbols).
fn tokens(text: &str) -> Vec<String> {
    text.split(|c: char| !(c.is_alphanumeric() || c == '_'))
        .filter(|t| !t.is_empty())
        .map(|t| t.to_ascii_lowercase())
        .collect()
}

/// Distinctive tokens: len ≥ 4 (drops stopwords-ish short noise).
fn distinctive(text: &str) -> Vec<String> {
    tokens(text).into_iter().filter(|t| t.chars().count() >= 4).collect()
}

/// Count marker hits with WORD-BOUNDARY semantics: an occurrence only
/// counts when the chars flanking it are not alphanumeric. Substring
/// containment is wrong here — "retrospective" contains "spec" and would
/// fire the test-content marker on meeting notes, teaching the net a
/// spurious shortcut. Multi-char markers like "#[test]" / "describe("
/// still match because their flanks are non-alphanumeric by construction.
fn word_hits(text: &str, words: &[&str]) -> f32 {
    let lower = text.to_lowercase();
    let mut hits = 0.0f32;
    for w in words {
        if w.is_empty() {
            continue;
        }
        let mut start = 0usize;
        while start + w.len() <= lower.len() {
            let Some(pos) = lower[start..].find(w) else { break };
            let abs = start + pos;
            let before_ok =
                abs == 0 || !lower[..abs].chars().next_back().is_some_and(|c| c.is_alphanumeric());
            let end = abs + w.len();
            let after_ok =
                end >= lower.len() || !lower[end..].chars().next().is_some_and(|c| c.is_alphanumeric());
            if before_ok && after_ok {
                hits += 1.0;
            }
            start = abs + w.len();
        }
    }
    (hits / (text.len() as f32 / 200.0 + 1.0)).min(1.0)
}

fn density(text: &str, pred: impl Fn(char) -> bool) -> f32 {
    let mut n = 0usize;
    let mut total = 0usize;
    for c in text.chars() {
        total += 1;
        if pred(c) {
            n += 1;
        }
    }
    if total == 0 {
        return 0.0;
    }
    (n as f32 / total as f32).min(1.0)
}

/// Distinct/total token ratio — low means repetitive/verbose material.
fn distinct_token_ratio(text: &str) -> f32 {
    let toks = tokens(text);
    if toks.is_empty() {
        return 1.0;
    }
    let distinct: std::collections::HashSet<&str> =
        toks.iter().map(|s| s.as_str()).collect();
    distinct.len() as f32 / toks.len() as f32
}

/// Path-like token density (`src/foo.rs`, `crate::y`, `./x`).
fn path_density(text: &str) -> f32 {
    let mut hits = 0.0f32;
    for tok in text.split_whitespace() {
        let t = tok.trim_matches(|c: char| {
            !c.is_alphanumeric() && c != '/' && c != '.' && c != ':' && c != '_'
        });
        if (t.contains('/') && t.len() >= 5 && !t.starts_with("http"))
            || t.contains("::")
            || t.ends_with(".rs")
            || t.ends_with(".js")
            || t.ends_with(".ts")
            || t.ends_with(".py")
            || t.ends_with(".md")
            || t.ends_with(".toml")
            || t.ends_with(".json")
        {
            hits += 1.0;
        }
    }
    (hits / (text.len() as f32 / 200.0 + 1.0)).min(1.0)
}

/// Code-symbol density: snake_case / CamelCase identifiers.
fn code_symbol_density(text: &str) -> f32 {
    let mut hits = 0.0f32;
    for tok in text.split_whitespace() {
        let t = tok.trim_matches(|c: char| !c.is_alphanumeric() && c != '_');
        let has_underscore_ident = t.contains('_') && t.chars().any(|c| c.is_alphabetic());
        let has_camel = {
            let mut lower_then_upper = false;
            let mut prev_lower = false;
            for c in t.chars() {
                if prev_lower && c.is_ascii_uppercase() {
                    lower_then_upper = true;
                    break;
                }
                prev_lower = c.is_ascii_lowercase();
            }
            lower_then_upper
        };
        if has_underscore_ident || has_camel {
            hits += 1.0;
        }
    }
    (hits / (text.len() as f32 / 200.0 + 1.0)).min(1.0)
}

/// Fraction of the candidate's distinctive tokens that appear in `other`.
fn overlap_ratio(text: &str, other: &str) -> f32 {
    let other_lower = other.to_lowercase();
    let mine = distinctive(text);
    if mine.is_empty() {
        return 0.0;
    }
    let hit = mine.iter().filter(|t| other_lower.contains(t.as_str())).count();
    (hit as f32 / mine.len() as f32).min(1.0)
}

/// Verbatim char-trigram hit: fraction of the task's char-3grams present in
/// the candidate. Catches exact phrasing the word-tokenizer splits.
fn trigram_hit(task: &str, text: &str) -> f32 {
    let t: Vec<char> = task.to_lowercase().chars().collect();
    if t.len() < 3 {
        return 0.0;
    }
    let lower = text.to_lowercase();
    let mut total = 0usize;
    let mut hit = 0usize;
    for i in 0..t.len().saturating_sub(2) {
        let gram: String = t[i..i + 3].iter().collect();
        if gram.chars().all(|c| c.is_whitespace()) {
            continue;
        }
        total += 1;
        if lower.contains(&gram) {
            hit += 1;
        }
    }
    if total == 0 {
        return 0.0;
    }
    (hit as f32 / total as f32).min(1.0)
}

/* ── BM25 over the candidate set ─────────────────────────────────── */

/// BM25 score of every candidate for the task query, computed over the
/// candidate set as the document collection. Returns raw scores in input
/// order. Deterministic (fixed term order, f32 accumulation in index order).
fn bm25_scores(task: &str, candidates: &[CandidateInput]) -> Vec<f32> {
    let query = distinctive(task);
    let n = candidates.len();
    if n == 0 || query.is_empty() {
        return vec![0.0; n];
    }
    // Document term frequencies + lengths.
    let doc_tokens: Vec<Vec<String>> = candidates.iter().map(|c| tokens(c.text)).collect();
    let doc_len: Vec<f32> = doc_tokens.iter().map(|t| t.len() as f32).collect();
    let avgdl = doc_len.iter().sum::<f32>() / n as f32;
    let avgdl = if avgdl <= 0.0 { 1.0 } else { avgdl };

    // Document frequency per query term (cap at the distinct query terms).
    let df: HashMap<&str, usize> = {
        let seen_in_doc: Vec<std::collections::HashSet<&str>> =
            doc_tokens.iter().map(|t| t.iter().map(|s| s.as_str()).collect()).collect();
        let mut df: HashMap<&str, usize> = HashMap::new();
        for q in &query {
            let mut count = 0usize;
            for s in &seen_in_doc {
                if s.contains(q.as_str()) {
                    count += 1;
                }
            }
            df.insert(q.as_str(), count);
        }
        df
    };

    let mut out = vec![0.0f32; n];
    for (di, toks) in doc_tokens.iter().enumerate() {
        let mut tf: HashMap<&str, usize> = HashMap::new();
        for t in toks {
            *tf.entry(t.as_str()).or_insert(0) += 1;
        }
        let dl = doc_len[di];
        let mut score = 0.0f32;
        for q in &query {
            let f = *tf.get(q.as_str()).unwrap_or(&0) as f32;
            if f == 0.0 {
                continue;
            }
            let n_containing = *df.get(q.as_str()).unwrap_or(&0) as f32;
            let idf = ((n as f32 - n_containing + 0.5) / (n_containing + 0.5) + 1.0).ln();
            let denom = f + BM25_K1 * (1.0 - BM25_B + BM25_B * dl / avgdl);
            score += idf * (f * (BM25_K1 + 1.0)) / denom;
        }
        out[di] = score;
    }
    out
}

/* ── Set-level precomputation ────────────────────────────────────── */

struct SetStats {
    emb: Vec<Vec<f32>>,
    task_emb: Vec<f32>,
    recent_emb: Vec<f32>,
    centroid: Vec<f32>,
    bm25: Vec<f32>,
    bm25_max: f32,
    /// BM25 rank per candidate, normalized: 0 = best, 1 = worst.
    bm25_rank: Vec<f32>,
    max_tokens: f32,
    n_norm: f32,
}

fn compute_stats(ctx: &RelevanceContext) -> SetStats {
    let emb: Vec<Vec<f32>> = ctx.candidates.iter().map(|c| embed_text(c.text)).collect();
    let task_emb = embed_text(ctx.task);
    let recent_emb = embed_text(ctx.recent);

    // Centroid of the candidate set (redundancy channel).
    let mut centroid = vec![0.0f32; EMBED_DIM];
    if !emb.is_empty() {
        for e in &emb {
            for (i, v) in e.iter().enumerate() {
                centroid[i] += v;
            }
        }
        let inv = 1.0 / emb.len() as f32;
        for v in centroid.iter_mut() {
            *v *= inv;
        }
    }

    let bm25 = bm25_scores(ctx.task, ctx.candidates);
    let bm25_max = bm25.iter().cloned().fold(0.0f32, f32::max);

    // Rank by BM25 descending; ties keep input order (stable, deterministic).
    let mut order: Vec<usize> = (0..bm25.len()).collect();
    order.sort_by(|&a, &b| {
        bm25[b].partial_cmp(&bm25[a]).unwrap_or(std::cmp::Ordering::Equal).then(a.cmp(&b))
    });
    let mut bm25_rank = vec![0.0f32; bm25.len()];
    let denom = (bm25.len().saturating_sub(1)).max(1) as f32;
    for (rank, &idx) in order.iter().enumerate() {
        bm25_rank[idx] = rank as f32 / denom;
    }

    let max_tokens = ctx
        .candidates
        .iter()
        .map(|c| c.text.len() as f32 / 4.0)
        .fold(1.0f32, f32::max);
    let n_norm = (ctx.candidates.len() as f32 / 32.0).min(1.0);

    SetStats { emb, task_emb, recent_emb, centroid, bm25, bm25_max, bm25_rank, max_tokens, n_norm }
}

/* ── Extraction ──────────────────────────────────────────────────── */

/// Extract the 37-feature vector for candidate `idx`. `stats` is the
/// precomputed set-level data from `compute_stats` (built once per call
/// site via `extract_all`).
fn extract(ctx: &RelevanceContext, idx: usize, st: &SetStats) -> [f32; RELEVANCE_FEATURES] {
    let cand = &ctx.candidates[idx];
    let mut f = [0.0f32; RELEVANCE_FEATURES];

    // 0: semantic similarity to the task.
    let sim_task = cosine(&st.emb[idx], &st.task_emb);
    f[0] = sim_task;

    // 1-2: BM25 over the candidate set (normalized score + rank).
    f[1] = if st.bm25_max > 0.0 { st.bm25[idx] / st.bm25_max } else { 0.0 };
    f[2] = st.bm25_rank[idx];

    // 3-5: lexical overlap with the task (term ratio, IDF-ish weighted by
    // distinctiveness, verbatim trigram hit).
    f[3] = overlap_ratio(cand.text, ctx.task);
    f[4] = overlap_ratio(ctx.task, cand.text); // task-side coverage
    f[5] = trigram_hit(ctx.task, cand.text);

    // 6-9: set context (position, set size, length, length ratio).
    let rank_denom = (ctx.candidates.len().saturating_sub(1)).max(1) as f32;
    f[6] = idx as f32 / rank_denom;
    f[7] = st.n_norm;
    let tok = cand.text.len() as f32 / 4.0;
    f[8] = (tok / 4000.0).min(1.0);
    f[9] = tok / st.max_tokens;

    // 10-13: kind one-hots.
    let kh = cand.kind.one_hots();
    f[10] = kh[0];
    f[11] = kh[1];
    f[12] = kh[2];
    f[13] = kh[3];

    // 14-15: brain strength + role (memories only).
    // clamp() passes NaN through — sanitize to neutral instead (Phase 1.3).
    f[14] = if cand.strength.is_finite() { cand.strength.clamp(0.0, 1.0) } else { 0.0 };
    f[15] = (cand.role as f32 / 8.0).min(1.0);

    // 16-18: duplication — max cosine to an already-kept candidate,
    // redundancy vs the candidate centroid, and a hard near-dup flag.
    let mut max_kept = 0.0f32;
    for &k in ctx.kept {
        if k == idx || k >= st.emb.len() {
            continue;
        }
        let c = cosine(&st.emb[idx], &st.emb[k]);
        if c > max_kept {
            max_kept = c;
        }
    }
    f[16] = max_kept;
    f[17] = cosine(&st.emb[idx], &st.centroid);
    f[18] = if max_kept >= 0.90 { 1.0 } else { 0.0 };

    // 19-26: shape channels.
    let path_src = if cand.path.is_empty() { cand.text } else { cand.path };
    f[19] = path_density(path_src);
    f[20] = extension_matches_task(cand.path, ctx.task);
    f[21] = code_symbol_density(cand.text);
    f[22] = density(cand.text, |c| c.is_ascii_uppercase()) * 5.0;
    if f[22] > 1.0 {
        f[22] = 1.0;
    }
    f[23] = density(cand.text, |c| matches!(c, '{' | '}' | '(' | ')' | ';' | '=' | ',')) * 4.0;
    if f[23] > 1.0 {
        f[23] = 1.0;
    }
    f[24] = density(cand.text, |c| c.is_ascii_digit()) * 5.0;
    if f[24] > 1.0 {
        f[24] = 1.0;
    }
    f[25] = 1.0 - distinct_token_ratio(cand.text);
    f[26] = cosine(&st.emb[idx], &BOILERPLATE_VEC);

    // 27: already visible in the recent history.
    if !ctx.recent.is_empty() {
        f[27] = cosine(&st.emb[idx], &st.recent_emb).max(overlap_ratio(cand.text, ctx.recent));
    }

    // 28-35: task×content interactions — the class where the label flips
    // with the TASK, not the candidate (§9). No threshold on a single
    // feature can express these; they are what the parameters learn.
    let task_lower = ctx.task.to_lowercase();
    let version_task = VERSION_TASK_WORDS.iter().any(|w| task_lower.contains(w));
    let behaviour_task = BEHAVIOUR_TASK_WORDS.iter().any(|w| task_lower.contains(w));
    let cand_version = word_hits(cand.text, VERSION_WORDS) > 0.05;
    let cand_test = word_hits(cand.text, TEST_CONTENT_WORDS) > 0.05;
    let stem = stem_match(ctx.task, cand.text);
    f[28] = if version_task && cand_version { 1.0 } else { 0.0 };
    f[29] = if behaviour_task && cand_test { 1.0 } else { 0.0 };
    // 30: semantic match with LOW lexical overlap — the synonym/needle
    // class. Gated on morphological corroboration: the bundled embedder's
    // char-trigram cosine has a high noise floor (shared suffix trigrams
    // like "-ion" inflate unrelated pairs into the 0.3-0.5 band), so a
    // bare cosine above floor is NOT a synonym signal — the task's word
    // stems must actually echo in the candidate.
    f[30] = if sim_task >= 0.30 && f[3] < 0.25 && stem >= 0.30 { sim_task } else { 0.0 };
    // 31: high lexical overlap but LOW semantic match — the wrong-topic trap.
    f[31] = if f[3] >= 0.40 && sim_task < 0.20 { f[3] } else { 0.0 };
    // 32: definition-site marker (a task symbol defined in the candidate).
    f[32] = definition_site(ctx.task, cand.text);
    // 33: never-use class (generated / lockfile / license / minified).
    f[33] = word_hits(cand.text, NEVER_USE_WORDS).max(if f[25] > 0.7 && f[21] > 0.3 { 0.5 } else { 0.0 });
    // 34: BM25 × semantic interaction.
    f[34] = f[1] * sim_task;
    // 35: task-sim gated on NOT already visible (a visible match is less new).
    f[35] = sim_task * (1.0 - f[27]);
    // 36: morphological stem match — fraction of the task's distinctive
    // tokens whose 5-char stem appears anywhere in the candidate. Catches
    // inflectional echoes the exact-word overlap channels miss
    // (migrates↔migration, evicts↔eviction, throttles↔throttle): the
    // synonym/needle class when the embedder's char-trigram cosine is
    // too coarse to separate it on its own (§6 embedder limit).
    f[36] = stem;

    f
}

/// Fraction of the task's distinctive tokens whose first five characters
/// (the morphological stem) appear in `text`. Deterministic: fixed token
/// order from the task.
fn stem_match(task: &str, text: &str) -> f32 {
    let mine = distinctive(task);
    if mine.is_empty() {
        return 0.0;
    }
    let lower = text.to_lowercase();
    let hit = mine
        .iter()
        .filter(|t| {
            let stem: String = t.chars().take(5).collect();
            stem.len() >= 4 && lower.contains(&stem)
        })
        .count();
    (hit as f32 / mine.len() as f32).min(1.0)
}

/// Does the candidate's file extension token appear in the task? (a `.rs`
/// file when the task names a `.rs` path).
fn extension_matches_task(path: &str, task: &str) -> f32 {
    if path.is_empty() {
        return 0.0;
    }
    let ext = match path.rsplit('.').next() {
        Some(e) if !e.is_empty() && e.len() <= 6 => e.to_ascii_lowercase(),
        _ => return 0.0,
    };
    let task_lower = task.to_lowercase();
    if task_lower.contains(&format!(".{ext}")) {
        return 1.0;
    }
    // Also match the file stem if it is a distinctive task token.
    if let Some(stem) = path.rsplit('/').next() {
        let stem = stem.to_ascii_lowercase();
        let stem = stem.split('.').next().unwrap_or("");
        if stem.len() >= 4 && task_lower.contains(stem) {
            return 0.5;
        }
    }
    0.0
}

/// Definition-site detection: the task names a code symbol (snake_case or
/// CamelCase, len ≥ 5) and the candidate contains a definition keyword
/// immediately before that symbol.
fn definition_site(task: &str, text: &str) -> f32 {
    let def_kw = ["fn ", "function ", "class ", "struct ", "def ", "const ", "impl ", "enum ", "type "];
    let task_syms: Vec<String> = task
        .split(|c: char| !(c.is_alphanumeric() || c == '_'))
        .filter(|t| {
            let n = t.chars().count();
            n >= 5 && (t.contains('_') || t.chars().any(|c| c.is_ascii_uppercase()))
        })
        .map(|t| t.to_string())
        .collect();
    if task_syms.is_empty() {
        return 0.0;
    }
    let lower = text.to_lowercase();
    for sym in &task_syms {
        let sym_l = sym.to_ascii_lowercase();
        for kw in &def_kw {
            if lower.contains(&format!("{kw}{sym_l}")) {
                return 1.0;
            }
        }
    }
    0.0
}

/// Embed every candidate once, compute the set-level stats, then extract
/// all vectors (the JS shim's batch path — embedding + BM25 are the
/// expensive parts).
pub fn extract_all(ctx: &RelevanceContext) -> Vec<[f32; RELEVANCE_FEATURES]> {
    let st = compute_stats(ctx);
    (0..ctx.candidates.len()).map(|i| extract(ctx, i, &st)).collect()
}

/* ── Tests ───────────────────────────────────────────────────────── */

#[cfg(test)]
mod tests {
    use super::*;

    fn cand(text: &'static str, kind: CandKind) -> CandidateInput<'static> {
        CandidateInput { text, kind, strength: 0.0, role: 0, path: "" }
    }

    fn cand_file(text: &'static str, path: &'static str) -> CandidateInput<'static> {
        CandidateInput { text, kind: CandKind::File, strength: 0.0, role: 0, path }
    }

    #[test]
    fn vector_shape_and_determinism() {
        let cands = [
            cand_file("fn parse_config reads the toml file and returns the settings struct", "src/config.rs"),
            cand("the weather in oslo is unrelated to the task at hand", CandKind::Web),
            cand("remember to use the ripgrep binary for searches", CandKind::Memory),
        ];
        let ctx = RelevanceContext {
            task: "fix the parse_config function in the config module",
            recent: "",
            candidates: &cands,
            kept: &[],
        };
        let a = extract_all(&ctx);
        let b = extract_all(&ctx);
        assert_eq!(a.len(), 3);
        for (va, vb) in a.iter().zip(b.iter()) {
            assert_eq!(va.len(), RELEVANCE_FEATURES);
            for (x, y) in va.iter().zip(vb.iter()) {
                assert_eq!(x.to_bits(), y.to_bits(), "extraction must be deterministic");
            }
        }
    }

    /// Phase 1.3 (§5.3): empty/whitespace, NUL, Unicode, and path-like
    /// candidate texts over empty and hostile tasks — every feature must
    /// stay finite and in band, never panic.
    #[test]
    fn hostile_candidates_stay_finite_and_bounded() {
        let texts: Vec<String> = vec![
            String::new(),
            "  \t ".into(),
            "\u{0}\u{0}".into(),
            "配列😀\u{2028}".into(),
            "crate::path::to::mod".into(),
            "x".repeat(60_000),
            "deprecated deprecated deprecated".into(),
        ];
        let cands: Vec<CandidateInput> = texts
            .iter()
            .enumerate()
            .map(|(i, t)| CandidateInput {
                text: t,
                kind: [CandKind::File, CandKind::Memory, CandKind::Web, CandKind::Other][i % 4],
                strength: if i % 2 == 0 { f32::NAN } else { 2.5 },
                role: (i * 90) as u8,
                path: if i % 3 == 0 { "" } else { "src/deep/path/mod.rs" },
            })
            .collect();
        let ctx = RelevanceContext {
            task: "\u{0}latest 配列 version 😀",
            recent: "",
            candidates: &cands,
            kept: &[0, 3],
        };
        let v = extract_all(&ctx);
        assert_eq!(v.len(), cands.len());
        for (i, vec) in v.iter().enumerate() {
            for (j, x) in vec.iter().enumerate() {
                assert!(x.is_finite(), "cand {i} feature {j} NaN/Inf: {x}");
                assert!((-1.0..=2.0).contains(x), "cand {i} feature {j} out of band: {x}");
            }
        }
    }

    #[test]
    fn bm25_ranks_on_task_match() {
        let cands = [
            cand("database migration schema tables columns indexes migration", CandKind::File),
            cand("a recipe for sourdough bread with a long fermentation", CandKind::Web),
        ];
        let ctx = RelevanceContext {
            task: "finish the database migration",
            recent: "",
            candidates: &cands,
            kept: &[],
        };
        let v = extract_all(&ctx);
        // The on-task candidate has the better (lower) BM25 rank and a
        // higher normalized BM25 score.
        assert!(v[0][1] > v[1][1], "on-task BM25 score must be higher");
        assert!(v[0][2] < v[1][2], "on-task BM25 rank must be better (lower)");
    }

    #[test]
    fn near_duplicate_of_kept_is_flagged() {
        let cands = [
            cand("the session token expires after twenty minutes of inactivity", CandKind::File),
            cand("the session token expires after twenty minutes of inactivity", CandKind::File),
            cand("an entirely different note about the cache eviction policy", CandKind::File),
        ];
        let ctx = RelevanceContext {
            task: "debug the auth session expiry",
            recent: "",
            candidates: &cands,
            kept: &[0], // candidate 0 already accepted
        };
        let v = extract_all(&ctx);
        assert!(v[1][16] > 0.9, "verbatim repeat of a kept candidate must read as dup");
        assert_eq!(v[1][18], 1.0, "near-dup flag must fire");
        assert!(v[2][16] < 0.6, "unrelated candidate must not");
    }

    #[test]
    fn definition_site_fires_for_named_symbol() {
        let cands = [
            cand("fn evict_expired walks the lru cache and drops stale entries", CandKind::File),
            cand("evict_expired is mentioned in passing in an unrelated changelog", CandKind::File),
        ];
        let ctx = RelevanceContext {
            task: "fix the evict_expired function in the cache",
            recent: "",
            candidates: &cands,
            kept: &[],
        };
        let v = extract_all(&ctx);
        assert_eq!(v[0][32], 1.0, "definition site must fire");
        assert_eq!(v[1][32], 0.0, "mere mention must not");
    }

    #[test]
    fn task_dependent_label_channels() {
        // A changelog candidate: version-channel fires only when the TASK
        // is about versions.
        let changelog = cand("changelog version 2.0 breaking change deprecated the old api", CandKind::File);
        let version_task = RelevanceContext {
            task: "what changed in the latest version upgrade",
            recent: "",
            candidates: std::slice::from_ref(&changelog),
            kept: &[],
        };
        let other_task = RelevanceContext {
            task: "fix the null pointer in the parser",
            recent: "",
            candidates: std::slice::from_ref(&changelog),
            kept: &[],
        };
        let vv = extract_all(&version_task);
        let vo = extract_all(&other_task);
        assert_eq!(vv[0][28], 1.0, "version-task × version-content must fire");
        assert_eq!(vo[0][28], 0.0, "non-version task must not fire the channel");
    }

    #[test]
    fn stem_match_fires_on_morphological_echo() {
        // The answer echoes the task's domain words in DIFFERENT word forms
        // (migrates↔migration): exact-word overlap stays partial, the stem
        // channel must still fire. Goal tasks carry generic verbs
        // (finish/work) that never echo, so the ceiling is the domain-word
        // fraction — here 2 of 4 distinctive tokens.
        let cands = [
            cand("the routine migrates the storage schema, rewriting each table and rebuilding the column indexes before the database is swapped live", CandKind::Other),
            cand("office logistics memo about desks, badges, and parking slots in the annex building", CandKind::Other),
        ];
        let ctx = RelevanceContext {
            task: "finish the database migration work",
            recent: "",
            candidates: &cands,
            kept: &[],
        };
        let v = extract_all(&ctx);
        assert!(v[0][36] >= 0.5, "morphological echo must fire the stem channel");
        assert!(v[1][36] < 0.3, "unrelated content must not");
    }
}
