//! Small, curated semantic families for the offline memory embedder trainer.
//!
//! These are intentionally short paraphrase families rather than a random
//! bag of sentences.  Four examples per family train the projector, one is
//! used for validation and one is held out for the final retrieval check.

pub struct Group {
    pub name: &'static str,
    pub examples: &'static [&'static str],
}

pub fn groups() -> &'static [Group] {    static GROUPS: &[Group] = &[
        Group {
            name: "memory",
            examples: &[
                "remember this project decision for the next session",
                "save this fact in the Sofuu brain so it can be recalled later",
                "keep this preference in long term memory across conversations",
                "store the important context and retrieve it when needed",
                "write this durable fact into memory for future work",
                "make this decision available to the assistant next time",
            ],
        },
        Group {
            name: "embedding",
            examples: &[
                "turn text into a vector for semantic similarity search",
                "create a local numeric representation of this sentence",
                "map related language into a compact embedding space",
                "compare two messages using their learned feature vectors",
                "the embedder converts words and phrases into coordinates",
                "generate a small semantic vector without an API call",
            ],
        },
        Group {
            name: "qtsq",
            examples: &[
                "QTSQ stores the session and conversation streams on disk",
                "read the custom qtsq container format for a saved session",
                "the persistence codec keeps Sofuu records in a QTSQ file",
                "decode the qtsq streams before restoring the conversation",
                "a brain file is serialized as a QTSQ container",
                "use the project QTSQ format for durable structured data",
            ],
        },
        Group {
            name: "compression",
            examples: &[
                "compress large session data to reduce disk usage",
                "only run the compressor when the payload is big enough",
                "the compressed archive should be smaller than the original",
                "avoid compression overhead for tiny files",
                "measure the ratio before choosing a compression strategy",
                "pack repeated conversation content efficiently",
            ],
        },
        Group {
            name: "encryption",
            examples: &[
                "do not encrypt the local brain file unless the user asks",
                "encryption protects data at rest with a secret key",
                "decrypt the vault before reading its stored contents",
                "the persistence layer should make the security choice explicit",
                "an encrypted session cannot be decoded without its password",
                "keep private conversation data protected on disk",
            ],
        },
        Group {
            name: "model",
            examples: &[
                "the tiny model predicts which context is useful",
                "run the local machine learning model before the language model",
                "a small neural network can advise the agent loop",
                "keep the model parameter count low for fast inference",
                "the learned gate scores a request without network access",
                "improve the predictor without increasing its parameter budget",
            ],
        },
        Group {
            name: "brain",
            examples: &[
                "the brain recalls related past outputs for context",
                "query cognitive memory before asking the main AI model",
                "old answers should be available when a task needs history",
                "the memory index ranks the most relevant stored facts",
                "recall should return useful records rather than every file",
                "use the brain to recover context after an interrupted run",
            ],
        },
        Group {
            name: "build",
            examples: &[
                "build the main Sofuu command line runtime",
                "compile the core binary while skipping the desktop app",
                "produce a release executable from the Rust workspace",
                "verify that the primary application builds successfully",
                "run the project build after changing the runtime code",
                "the shipped CLI comes from the core package",
            ],
        },
        Group {
            name: "testing",
            examples: &[
                "run the tests after implementing the memory change",
                "a regression test should catch corrupted model artifacts",
                "verify the behavior on a clean isolated fixture",
                "test both the old format and the new migration path",
                "the acceptance suite checks deterministic inference",
                "add coverage for the failure case before shipping",
            ],
        },
        Group {
            name: "rust",
            examples: &[
                "the core runtime is implemented in Rust",
                "add a public module to the Rust library crate",
                "use safe ownership around the native memory handle",
                "the compiler should reject invalid vector dimensions",
                "keep the implementation in the existing Rust codebase",
                "Rust provides the deterministic offline inference path",
            ],
        },
        Group {
            name: "javascript",
            examples: &[
                "the agent driver calls the Rust functions from JavaScript",
                "update the shipped JS memory helper to use the new embedder",
                "the QuickJS script opens a brain and recalls records",
                "keep the public JavaScript API compatible with existing code",
                "the conversation loop is written in the Sofuu JS driver",
                "pass the semantic vector through the JavaScript binding",
            ],
        },
        Group {
            name: "files",
            examples: &[
                "write the result into the project output folder",
                "read the existing file before deciding what to change",
                "keep related artifacts together under the Sofuu directory",
                "the path points to a local workspace file",
                "do not overwrite an unrelated user file",
                "open the saved document and inspect its contents",
            ],
        },
        Group {
            name: "git",
            examples: &[
                "preserve the dirty worktree and do not reset user changes",
                "inspect the diff before editing an already modified file",
                "commit only the files that belong to this implementation",
                "the repository has unrelated uncommitted work",
                "compare the working tree with the current HEAD revision",
                "avoid destructive checkout operations in the project",
            ],
        },
        Group {
            name: "error",
            examples: &[
                "return a clear error when the model file is corrupted",
                "fail closed instead of silently returning empty memory",
                "report the reason that the requested operation could not run",
                "invalid input should be rejected before native code reads it",
                "keep the old data safe when a migration fails",
                "surface a useful diagnostic for a missing artifact",
            ],
        },
        Group {
            name: "network",
            examples: &[
                "send the request to the configured remote AI provider",
                "the network call can fail while the local brain remains usable",
                "stream the model response over the provider connection",
                "a remote completion requires an authenticated endpoint",
                "retry a transient connection failure with a bounded delay",
                "keep semantic memory inference offline without network latency",
            ],
        },
        Group {
            name: "provider",
            examples: &[
                "select the model provider and its configured model name",
                "provider settings choose the endpoint used for completion",
                "switch from the default service to a local compatible server",
                "the active provider supplies the language model response",
                "configure credentials and a base URL for the AI service",
                "the embedding provider is separate from the chat provider",
            ],
        },
        Group {
            name: "configuration",
            examples: &[
                "change the runtime setting in the Sofuu configuration file",
                "the configuration controls memory scope and model behavior",
                "read the saved options before starting the agent",
                "an explicit setting should override the default value",
                "keep configuration names stable across releases",
                "turn a feature on or off through the user config",
            ],
        },
        Group {
            name: "output-archive",
            examples: &[
                "archive each completed answer with a timestamp",
                "keep old outputs so the model can recover lost context",
                "store generated result files under the outputs directory",
                "retrieve the earlier answer by its recorded time",
                "the output history helps diagnose what went wrong",
                "preserve prior run artifacts instead of deleting them",
            ],
        },
        Group {
            name: "session",
            examples: &[
                "restore the conversation session from its saved state",
                "a session contains messages settings and execution history",
                "continue the previous run after reopening the project",
                "persist the current conversation before shutting down",
                "the session file is the durable source for a resumed task",
                "load all relevant session context at startup",
            ],
        },
        Group {
            name: "agent",
            examples: &[
                "define an agent with tools identity and a memory scope",
                "the agent loop delegates a subtask to another worker",
                "an agent should remember only its private entity records",
                "run the assistant with a bounded step and token budget",
                "the main agent coordinates tools and model calls",
                "a specialized agent handles one functional responsibility",
            ],
        },
        Group {
            name: "tools",
            examples: &[
                "the assistant calls a tool to inspect the workspace",
                "record the tool result before composing the final answer",
                "a tool invocation may return data or an error",
                "choose the right function for the requested operation",
                "the agent can use filesystem and web tools during a task",
                "avoid repeating the same tool call when the result is unchanged",
            ],
        },
        Group {
            name: "performance",
            examples: &[
                "the local embedding lookup should be fast enough for every turn",
                "avoid allocating a large vector when a compact one is sufficient",
                "cache the model and keep inference latency predictable",
                "reduce disk and memory overhead without losing useful context",
                "the hot path must remain cheap under a long conversation",
                "measure latency before and after the optimization",
            ],
        },
        Group {
            name: "migration",
            examples: &[
                "convert old memory vectors into the new semantic space safely",
                "migrate legacy brain records without mixing incompatible dimensions",
                "write a verified replacement and retain a recoverable backup",
                "upgrade the stored index only after the new file passes checks",
                "re-embed old text records during a versioned migration",
                "a failed migration must leave the original brain intact",
            ],
        },
        Group {
            name: "security",
            examples: &[
                "do not expose secrets in logs or generated diagnostics",
                "validate file paths before reading or replacing data",
                "the runtime should fail safely on untrusted input",
                "protect user data while keeping local operation transparent",
                "avoid accepting a malformed artifact as a valid model",
                "security checks belong at the persistence boundary",
            ],
        },
        Group {
            name: "planning",
            examples: &[
                "write the implementation plan before changing the code",
                "the plan should define stable interfaces and acceptance gates",
                "separate the proposed work from the actual implementation",
                "document the design decisions and the rollback strategy",
                "make a detailed plan that respects the existing architecture",
                "review the plan before proceeding to the next phase",
            ],
        },
    ];
    GROUPS
}

/// Associative paraphrase families: the queries REPHRASE or ASSOCIATE rather
/// than echo memory tokens ("why were users failing to sign in?" must reach
/// memories about login timeouts and pool exhaustion).  This is the skill the
/// acceptance corpus's hardest category demands; procedural slot families
/// cannot teach it.  Each entry is 3 memories followed by 4 queries.
pub const ASSOC_FAMILIES: [&[&str]; 39] = [
    &[
        "The API gateway rate limiter admits bursts of twenty requests per client before the token bucket empties; steady state is five per second.",
        "Burst policy: twenty-shot bucket per client, refilling at five requests per second; beyond that the gateway answers 429.",
        "Clients can spike to twenty requests instantly, then the bucket refills at five a second until the next spike.",
        "how big a burst can a client send before throttling?",
        "what happens when a client exceeds their quota?",
        "why did the gateway return 429?",
        "request pacing limits",
    ],
    &[
        "Purging the CDN edge takes up to fifteen minutes to reach every POP; during that window users may see the stale asset.",
        "After a purge request, each edge location drops the object within fifteen minutes — until then the old asset keeps serving.",
        "Cache invalidation is not instant: allow a quarter hour for the purge to propagate to all edge locations.",
        "how long until removed assets disappear from the edge?",
        "why do some users still see the old banner image?",
        "cache invalidation delay",
        "how do I force the CDN to refresh?",
    ],
    &[
        "The users table migration takes an ACCESS EXCLUSIVE lock, so it must run inside the low-traffic window or requests queue behind it.",
        "Deploy note: the ALTER TABLE on users blocks all reads and writes while it runs — schedule it in the maintenance window.",
        "We froze deploys during the users-table migration because the exclusive lock stalls every request until it finishes.",
        "why did the API stall during the last deploy?",
        "when can the table change run safely?",
        "database migration locking rules",
        "what blocks requests while altering users?",
    ],
    &[
        "Nightly backups keep seven daily, four weekly and six monthly copies; anything older is pruned by the retention sweeper.",
        "Retention: 7 daily snapshots, 4 weekly, 6 monthly — the sweeper deletes beyond that at 04:00.",
        "Backup policy is grandfather-father-son: dailies for a week, weeklies for a month, monthlies for half a year.",
        "how long do we keep old backups?",
        "when are stale snapshots deleted?",
        "backup retention schedule",
        "disk filled with old backup files — what prunes them?",
    ],
    &[
        "Service keys rotate every ninety days; the old key stays valid for another day so deployments can catch up.",
        "Credential policy: rotate every 90 days with a one-day overlap where both keys work.",
        "Keys expire quarterly, and the previous one keeps authenticating for twenty-four hours to make the swap painless.",
        "how often do service credentials expire?",
        "will the old key stop working immediately after rotation?",
        "key lifetime and overlap rules",
        "auth started failing right after we rotated — why?",
    ],
    &[
        "Reindexing the search corpus takes about forty minutes; queries keep hitting the old index until the alias flips.",
        "The reindex job builds a shadow index for roughly forty minutes, then the alias switch makes it live atomically.",
        "Search stays up during reindexing: we build the new index in parallel and flip the read alias when it catches up.",
        "can search go down while rebuilding the index?",
        "how long does a full reindex take?",
        "how do new documents become searchable?",
        "index rebuild procedure",
    ],
    &[
        "When the load balancer health check fails, websockets reconnect in a thundering herd; the client now applies full jitter backoff up to thirty seconds.",
        "Reconnect storms after LB blips are fixed by jittered backoff — clients wait a random 0-30s before redialing.",
        "The mobile clients used to redial simultaneously; randomized backoff up to half a minute spreads the reconnect wave.",
        "why did the servers drown in reconnects after the blip?",
        "how do clients recover from a dropped socket?",
        "websocket reconnect policy",
        "connection storm mitigation",
    ],
    &[
        "The thumbnailer holds decoded frames in RAM, so a 50-megapixel upload can spike the worker past its 2 GiB cap and get OOM-killed.",
        "Workers die on huge uploads: the image pipeline decodes the full frame first, and anything above ~2 GiB RSS triggers the OOM killer.",
        "We cap uploads at 25 megapixels now; bigger files blew the thumbnailer's memory limit and restarted the pod.",
        "why does the uploader crash on huge photos?",
        "what size image is safe to upload?",
        "image worker OOM root cause",
        "memory limits for the media pipeline",
    ],
    &[
        "Exports larger than 100k rows are cut over to the async job queue because the synchronous request times out at sixty seconds.",
        "The export endpoint dies at the 60-second proxy timeout for big reports; anything over 100,000 rows must go through the background worker.",
        "Big CSV downloads fail with a gateway timeout — the rule is: sync exports only under 100k rows, the rest are emailed when the job finishes.",
        "why does downloading a big report fail?",
        "how do I export a very large dataset?",
        "export size limits",
        "what happens when a report takes too long?",
    ],
    &[
        "New features roll out through flags in stages: 1% internal, 10% beta, then 100% — each stage soaks for a day.",
        "Flag rollout ladder: internal first, then a tenth of traffic, then everyone, with a day between steps.",
        "We never ship dark: every feature enters through the flag stages and soaks 24 hours before widening.",
        "how does a new feature reach all users?",
        "what are the rollout stages?",
        "why is the feature only visible to some accounts?",
        "gradual release process",
    ],
    &[
        "Messages that fail five deliveries park in the dead-letter topic; replay is manual through the ops CLI after the root cause is fixed.",
        "The DLQ holds events that exhausted their retries; we replay them by hand once the underlying bug is patched.",
        "Don't auto-retry the dead-letter queue — a human replays it with the ops tool after confirming the consumer is healthy.",
        "where do failed events end up?",
        "how are stuck messages recovered?",
        "can the dead-letter queue replay itself?",
        "what happens to events that keep failing?",
    ],
    &[
        "The DNS cutover uses a 300-second TTL; old records can keep answering for five minutes after the switch.",
        "During the migration we dropped the TTL to five minutes so the cutover propagates within one TTL cycle.",
        "Resolvers may serve stale answers for up to five minutes after the cutover because that was the record's TTL.",
        "why did some users reach the old server after the switch?",
        "how long does a DNS change take to propagate?",
        "record TTL during migration",
        "dns cutover timing",
    ],
    &[
        "List endpoints cap page size at 200 items; larger windows must use the cursor, which streams indefinitely.",
        "Offset pagination stops at 200 per page — anything bigger has to follow the cursor links instead.",
        "We reject page sizes above 200; deep scans should walk the opaque cursor rather than asking for giant pages.",
        "what's the maximum number of items per page?",
        "how do I fetch more than the page limit?",
        "pagination caps",
        "why does page_size=1000 get rejected?",
    ],
    &[
        "The repo scanner blocks any push containing live credential patterns; the author must revoke and rotate before the push is accepted.",
        "Pushes fail closed when the scanner smells a key: rotate the credential first, then force-push the cleaned history.",
        "CI rejects commits matching secret patterns — the fix is revoking the leaked key, not silencing the scanner.",
        "why was my push rejected for secrets?",
        "what do I do if I committed an API key?",
        "credential leak procedure",
        "how are secrets kept out of the repo?",
    ],
    &[
        "Application logs live in the hot store for fourteen days, then compress into cold storage for a year.",
        "Two-tier logging: two weeks searchable, after which logs compress into the year-long archive.",
        "After fourteen days the log indexer drops entries from search, but nothing is deleted until twelve months pass.",
        "how far back can I search the logs?",
        "when are old logs deleted?",
        "log retention policy",
        "why did last month's log lines vanish from search?",
    ],
    &[
        "Kubernetes evicts pods that exceed their memory request by a wide margin; set requests to the observed p95 to stay safe.",
        "The evicter kills best-effort pods first — our workers must declare their real memory usage as a request.",
        "Pods restart during peak hours because their memory requests were set far below actual usage; right-sizing fixed it.",
        "why do the workers restart every afternoon?",
        "how do I stop the pods from being evicted?",
        "resource request guidance",
        "what triggers the scheduler to kill a pod?",
    ],
    &[
        "The mobile app refreshes its token only when a request returns 401; a clock skew over five minutes causes a refresh loop.",
        "Refresh storms came from device clocks drifting: the app treats 401 as 'refresh', so skewed clocks loop forever.",
        "Fix for the auth loop: sync device time and require a five-minute skew guard before attempting a refresh.",
        "why does the app keep asking for new tokens?",
        "what causes the login loop on phones?",
        "token refresh trigger conditions",
        "auth failures right after the timezone change?",
    ],
    &[
        "Marketing emails must send from the verified subdomain with DKIM aligned, or the provider routes them to spam.",
        "Bounce spikes traced back to unaligned DKIM: the sending subdomain has to match the verified domain exactly.",
        "Deliverability rule: aligned DKIM + verified subdomain or the mails land in the spam folder.",
        "why do our newsletters land in spam?",
        "what makes an email pass the provider's filter?",
        "sender reputation requirements",
        "customers stopped receiving our mail",
    ],
    &[
        "Uploads land in the hot bucket and transition to infrequent access after thirty days, then to glacier at ninety.",
        "Storage lifecycle: 30 days hot, then infrequent access, then archive at the 90-day mark.",
        "Old artifacts are not deleted — they cool down: standard for a month, infrequent for two more, then archived.",
        "when do uploaded files move to cold storage?",
        "are old artifacts ever deleted?",
        "storage tier rules",
        "where did last quarter's build artifacts go?",
    ],
    &[
        "The GraphQL resolver batches nested lookups through a dataloader, capping at fifty keys per round trip.",
        "We killed the N+1 problem by batching child queries — the loader coalesces up to 50 keys per call.",
        "Nested field performance is guarded by the dataloader; without it, a single query could fire hundreds of SQL calls.",
        "why was the nested query so slow?",
        "how are related objects fetched?",
        "query performance for deep results",
        "database load from GraphQL resolvers",
    ],
    &[
        "When the phone comes back online, conflicting edits resolve last-writer-wins per field, not per document.",
        "Sync conflicts merge at field granularity: the newest edit to each field survives, so two people can edit one note safely.",
        "Offline edits replay in order and per-field last-write-wins picks a winner only where edits truly collide.",
        "what happens when two devices edit the same note?",
        "how are sync conflicts resolved?",
        "merge rules for offline changes",
        "did my teammate's edit get lost?",
    ],
    &[
        "The stream consumer applies backpressure by pausing the reader at 10k buffered messages instead of dropping them.",
        "Nothing gets dropped under load: the pipeline pauses upstream once the buffer holds ten thousand messages.",
        "Our stance is pause-not-drop — the consumer signals the source to stop when the buffer crosses its high watermark.",
        "do we lose events when the queue fills?",
        "how does the pipeline handle surges?",
        "buffer limits and backpressure",
        "what protects the consumer from floods?",
    ],
    &[
        "Volumes warn at 80% full and page at 90%; the alert includes the three largest directories to make triage fast.",
        "Disk alerts fire in two stages — a warning at 80% and a page at 90% with the top-three space hogs attached.",
        "We get a heads-up when a volume crosses eighty percent so cleanup happens before the ninety percent page.",
        "when do we get alerted about full disks?",
        "what does the disk page include?",
        "storage alert thresholds",
        "the server almost filled up — why no warning?",
    ],
    &[
        "If the recommendation service is slow, the page renders without it after 200 ms rather than blocking the whole load.",
        "Recommendations are a nice-to-have: the page stops waiting at 200 ms and renders the rest regardless.",
        "Timeouts to the recommender are capped at 200 ms so a slow model never delays the whole page.",
        "why does the page load even when recommendations hang?",
        "how long do we wait for the recommender?",
        "degradation behavior for optional services",
        "is the recommender blocking the page?",
    ],
    &[
        "Log lines beyond the daily per-service budget are sampled at one in ten, but errors and stack traces are never sampled.",
        "High-volume services keep their full error logs: sampling applies to info and debug traffic only, at 10%.",
        "Log volume policy: debug and info lines are sampled to a tenth past the daily budget; failures always log in full.",
        "why are some log lines missing?",
        "which logs can be trusted to be complete?",
        "log sampling rules",
        "are error logs thinned out?",
    ],
    &[
        "The config service reloads from disk only when the file's mtime changes; identical rewrites are ignored to avoid pointless restarts.",
        "Config watchers trigger on mtime, not on writes — re-saving the same content does not restart anything.",
        "Reloads happen on real file changes: the watcher compares modification times and skips no-op rewrites.",
        "why didn't the config reload after I re-saved it?",
        "what triggers a config reload?",
        "config reload triggers",
        "does saving the same config restart the service?",
    ],
    &[
        "Abandoned carts are re-emailed after exactly twenty hours — early enough to feel same-day, late enough to not collide with the original receipt.",
        "The win-back email lands twenty hours after abandonment, by design: sooner collides with the order receipt, later loses the impulse.",
        "Cart recovery timing: a single reminder at the twenty-hour mark, chosen from open-rate testing.",
        "when do abandoned-cart emails go out?",
        "how was the reminder timing chosen?",
        "win-back email schedule",
        "why twenty hours for the cart reminder?",
    ],
    &[
        "Every feature flag has a mandatory expiry date; the nightly job files tickets for flags that outlived ninety days.",
        "Flags are born with a death date — the linter refuses to merge one without an expiry, and a bot flags the stragglers.",
        "Long-lived flags are treated as tech debt: expiry is required at creation, and the ninety-day report names owners.",
        "what happens to old feature flags?",
        "do flags ever get cleaned up?",
        "flag lifecycle rules",
        "who removes stale flags?",
    ],
    &[
        "The migration runner refuses down-migrations that would drop data without an explicit allow flag in the ticket.",
        "Destructive down-steps are blocked by default; the runner demands an override constant that the on-call must paste.",
        "Safety rail on migrations: any down step that drops columns or tables needs a written override, else the runner aborts.",
        "why did the rollback migration refuse to run?",
        "when can a migration drop data?",
        "rollback safety rules",
        "what blocks destructive migrations?",
    ],
    &[
        "Client libraries read the retry-after header first and fall back to a fixed backoff only when the server omits it.",
        "Backoff honors the server's hint: retry-after wins, and the library's own timer is just a fallback for silent servers.",
        "The pacing contract: servers that speak retry-after set the rhythm; otherwise the client waits its default.",
        "do clients respect the retry-after header?",
        "how do clients decide when to retry?",
        "client retry pacing rules",
        "what happens when the server sends no retry hint?",
    ],
    &[
        "Onboarding tours auto-dismiss after the third session; power users flagged the tour as noise in the survey.",
        "The product tour stops nagging by session three — survey data showed experienced users hated it.",
        "Tour frequency rule: it rides along at most twice, and the third session is a clean start.",
        "when does the onboarding tour stop?",
        "why did the tour disappear?",
        "tour display rules",
        "does the tour keep showing for new users?",
    ],
    &[
        "Heap profiles are only kept for crashes with a reproducer; one-off OOMs keep stack traces but drop the full heap dump.",
        "Heap dumps are heavy, so they are attached only to reproducible crashes; one-shot OOMs keep the cheaper stack summary.",
        "Crash artifact policy: full heap dumps for reproducible cases, stack traces for the rest.",
        "why can't I get a heap dump for my crash?",
        "when is a full heap dump saved?",
        "crash artifact retention",
        "what do we keep from OOM crashes?",
    ],
    &[
        "The billing clock rounds each metered minute up to the next whole minute but never rounds twice across a month boundary.",
        "Metered usage bills minute-granular: partial minutes round up once, and month boundaries never re-round them.",
        "Rounding happens at ingestion, exactly once — a 61-second call bills as two minutes, and boundary months do not double-round.",
        "how are partial minutes billed?",
        "does usage round up across month boundaries?",
        "metering rounding rules",
        "why was a one-second call billed a full minute?",
    ],
    &[
        "Contract draft PDFs are regenerated on open, never cached, so the pricing table always reflects the current quarter.",
        "No stale quotes: the draft generator runs per view because cached PDFs once quoted last quarter's prices.",
        "Draft contracts are always fresh — regeneration on every open, no document cache, to kill stale pricing.",
        "why is opening the draft slow?",
        "can the quote PDF be stale?",
        "draft document freshness",
        "why no cache for contract PDFs?",
    ],
    &[
        "The support widget routes Spanish and Portuguese chats to the LATAM queue and everything else by timezone alone.",
        "Chat routing logic: language decides LATAM versus global, then the agent's timezone fills the rest.",
        "Spanish and Portuguese go to the LATAM team; other languages are routed by support hours in the customer's timezone.",
        "how do chats get routed to agents?",
        "who answers Spanish-language chats?",
        "chat routing rules",
        "what decides which queue a chat lands in?",
    ],
    &[
        "Preflight checks reject deploys if the migration that the release depends on has not yet run on the staging database.",
        "Deploy gating: the release pipeline verifies staging migrations first; a missing one aborts the rollout before any pod changes.",
        "No deploy skips its schema work: preflight compares applied migrations on staging against the release manifest.",
        "why was the deploy blocked at preflight?",
        "what does preflight check before deploying?",
        "deploy gating rules",
        "can a release ship before its migration runs?",
    ],
    &[
        "Rate limits are enforced per API token, not per account, so one compromised key cannot throttle the whole team.",
        "Token-level throttling: quotas attach to keys, and a hammered token leaves its siblings untouched.",
        "A noisy or stolen key burns only its own budget — limits are per credential, never pooled at the account.",
        "does one busy key throttle the whole account?",
        "where are rate limits attached?",
        "throttling scope rules",
        "why did the other keys keep working during the incident?",
    ],
    &[
        "The diff viewer fetches at most three blob versions per row; older history links out to the commit browser.",
        "Row expansion caps at three versions inline — deeper history redirects to the full log view.",
        "Performance rule for the diff UI: three in-line ancestors, then a link out, so wide PRs stay responsive.",
        "why can't I see all versions in the diff row?",
        "how deep does inline history go?",
        "diff viewer limits",
        "where do old versions live?",
    ],
    &[
        "Announcements dismiss for ninety days per user, but severity-one banners override the dismissal and stay pinned.",
        "Banners respect snooze — ninety days — except sev-one notices, which pin above the fold regardless.",
        "Dismissal semantics: user snooze wins for normal notices, never for severity-one emergencies.",
        "why is the banner back after I dismissed it?",
        "can a banner be permanently hidden?",
        "announcement dismissal rules",
        "which banners ignore snooze?",
    ],
];

/// Short-query scenario families: long, concrete memories probed by SHORT
/// queries — including bare noun phrases with policy head-nouns ("retry
/// policy", "root cause", "size limits") that never appear in the memories.
/// Mirrors the acceptance corpus's query style, on topics the corpus does
/// not cover.  Each entry: 3 memories + 4 queries.
pub const ASSOC_SHORT: [&[&str]; 14] = [
    &[
        "The nightly cron jobs anchor to the server clock, so on daylight-saving nights the 02:30 window either repeats or skips; the scheduler now pins jobs to UTC.",
        "Job schedules are stored in UTC and converted at dispatch — that is why the billing roll ran once, not twice, through the last clock change.",
        "Cron drift report: repeated and skipped runs traced to local-time anchors; the fix stores every schedule as UTC offsets.",
        "why did the nightly job run twice in October?",
        "how are scheduled jobs affected by clock changes?",
        "cron timing rules",
        "scheduled task policy",
    ],
    &[
        "Queue workers autoscale on backlog age: below one minute the fleet holds at three, past five minutes it doubles up to twelve.",
        "The autoscaler watches the oldest pending job — when it ages past five minutes, new workers join until the backlog drains.",
        "Worker count policy: minimum three, maximum twelve, driven by how long the oldest queued task has waited.",
        "when do extra workers spin up?",
        "what decides the number of queue workers?",
        "worker autoscaling rules",
        "backlog capacity policy",
    ],
    &[
        "Dashboard aggregates cache for five minutes; a manual refresh bypasses the cache but is rate-limited to once per minute.",
        "Stale numbers on the overview page are expected within the five-minute cache window; the refresh button forces a rebuild.",
        "Cache lifetime for dashboard tiles is 300 seconds, with an explicit bypass that any user can trigger once a minute.",
        "why is the dashboard showing old numbers?",
        "how long do dashboard tiles stay cached?",
        "cache expiry policy",
        "stale data duration",
    ],
    &[
        "The events table carries eleven indexes; nightly writes slow-logged past 200 ms traced to the three never-used ones, which were dropped.",
        "Index bloat review: writes pay for every index, so unused ones from an old feature were removed and insert latency halved.",
        "Database policy: an index must justify itself with usage stats each quarter, or it gets dropped.",
        "why did inserts get slower over time?",
        "when does an index get removed?",
        "index maintenance policy",
        "write performance rules",
    ],
    &[
        "Push notifications cap at three per user per day, except critical security alerts; marketing sends share a separate hourly budget.",
        "The mobile push quota exists because uninstall rates climbed when users got more than three alerts a day.",
        "Notification policy: three daily per user, security alerts exempt, and the marketing channel is throttled independently.",
        "how many pushes can we send a user?",
        "why did daily notifications stop mid-campaign?",
        "notification rate limits",
        "mobile alert quotas",
    ],
    &[
        "Bulk CSV imports reject the whole file when more than 1% of rows fail schema checks; the error report lists the first fifty bad rows.",
        "Import validation is all-or-nothing above the 1% error threshold — partial loads caused duplicate invoices last quarter.",
        "Row-level rules for uploads: required columns present, dates ISO format, amounts positive; too many failures abort the file.",
        "why was my contact upload rejected?",
        "how are bad rows in an import handled?",
        "import validation rules",
        "bulk upload limits",
    ],
    &[
        "Signed download links expire after fifteen minutes and are bound to the requester's IP range; expired links return 403 with a refresh hint.",
        "Share links are short-lived on purpose — fifteen minutes, single range — because revocation of long-lived URLs was impossible.",
        "Expiry policy for file links: quarter-hour validity, IP-bound, one renewal click before the signer refuses.",
        "how long do download links stay valid?",
        "why did the shared file link stop working?",
        "link expiry policy",
        "secure sharing duration",
    ],
    &[
        "Service-to-service calls require mutual TLS with certs from the internal CA, rotated every thirty days by the mesh agent.",
        "A failed handshake between checkout and pricing traced to a pod still holding a rotated certificate — the mesh agent re-issued it.",
        "Internal traffic policy: every call is mTLS, certificates live thirty days, and the sidecar renews them automatically.",
        "how do internal services authenticate each other?",
        "why did one service call fail its handshake?",
        "internal traffic encryption",
        "certificate rotation rules",
    ],
    &[
        "Invoices compute VAT from the buyer's country code: EU reverse-charge for valid business IDs, standard rates otherwise.",
        "Total mismatches on invoices traced to the tax table — the buyer's region decides the rate, and business IDs flip EU customers to reverse-charge.",
        "Billing tax rules: country-driven rates, verified VAT numbers switch to reverse-charge, and the line items reprice on change.",
        "how is tax computed for EU customers?",
        "why does the invoice total differ from the quote?",
        "tax calculation rules",
        "regional pricing policy",
    ],
    &[
        "Search expands queries through the synonym table — 'mobile' also matches 'phone' results — but only in the default index language.",
        "Relevance tuning docs: synonyms load from a versioned table, apply at query time, and never fire inside quoted phrases.",
        "Why 'laptop' finds 'notebook' hits: the synonym expansion stage rewrites the query before ranking, per language.",
        "why does one word find another word's results?",
        "how is query matching expanded?",
        "synonym handling rules",
        "search relevance tuning",
    ],
    &[
        "The audit exporter writes each compliance event to two destinations: the operational log for triage and the WORM bucket for legal holds.",
        "Compliance events are dual-written — the ops log gets a copy for debugging, and the write-once archive keeps the legal copy.",
        "Every regulated event lands twice: once where engineers read it, once where nobody can rewrite it.",
        "where does audit data get written?",
        "can compliance records be rewritten?",
        "audit storage rules",
        "who can edit the legal archive?",
    ],
    &[
        "A schema change is only 'compatible' if last month's binary can still decode today's data; the CI job proves it with an old build.",
        "Backward compatibility is tested, not assumed: CI replays fresh fixtures through a month-old binary every night.",
        "Wire-format policy: the definition of compatible is that last month's release still parses today's payloads — a nightly job enforces it.",
        "how is schema compatibility verified?",
        "what makes a format change compatible?",
        "wire compatibility rules",
        "who checks that old builds still read new data?",
    ],
    &[
        "When the build cache hits 80% of its quota, jobs stop downloading new entries and evict by least-recently-used instead.",
        "Cache pressure policy: at eighty percent of quota the cache stops growing and starts recycling cold entries.",
        "The artifact cache has a soft ceiling — past 80% it turns over LRU entries rather than growing the volume.",
        "why did the build cache stop growing?",
        "what happens when the cache fills up?",
        "artifact cache policy",
        "cache eviction rules",
    ],
    &[
        "Feature rollouts ramp 1% → 5% → 25% → 100%, and each ramp stage requires a clean error-rate signal for a full day.",
        "Progressive delivery: the four-step ramp waits a day of healthy metrics between each increase.",
        "No flag flips straight to everyone: the ramp ladder is 1, 5, 25, then 100 percent with a 24-hour gate at each step.",
        "how quickly does a feature reach everyone?",
        "what gates each rollout increase?",
        "rollout ramp schedule",
        "can a feature go to 100% on day one?",
    ],
];
pub const ASSOC_VAL: [&[&str]; 10] = [
    &[
        "Every outbound webhook carries an HMAC signature computed with the endpoint's own secret and a timestamp to stop replay.",
        "Receivers verify the signature over the raw body plus the sent-at header; a five-minute window rejects stale replays.",
        "Signing rule: HMAC-SHA256 with the per-endpoint secret over body and timestamp; anything older than five minutes is dropped.",
        "how do receivers trust a webhook?",
        "what stops someone replaying an old delivery?",
        "webhook verification rules",
        "is the payload signed?",
    ],
    &[
        "On login the session id is always regenerated, so a pre-auth cookie can never be replayed into an authenticated session.",
        "We rotate the session identifier at every privilege change — fixation via a planted cookie is structurally impossible.",
        "Auth hardening: new session id on login and on role escalation; old ids are invalidated immediately.",
        "how is session hijacking via cookies prevented?",
        "what happens to the session id at login?",
        "session security rules",
        "can an attacker pin a session?",
    ],
    &[
        "Payment submissions carry an idempotency key; retries with the same key return the original receipt instead of double-charging.",
        "The charging endpoint dedups on the client-supplied idempotency token for twenty-four hours.",
        "Network retries are safe: same key, same result — the first receipt is cached for a day and replayed.",
        "can a retry charge the customer twice?",
        "how are duplicate submissions handled?",
        "idempotency rules",
        "what does the client send to retry safely?",
    ],
    &[
        "Every privileged action lands in the audit trail with actor, target, before/after values, and is immutable.",
        "The audit log is append-only: who changed what, from which address, with the old and new values side by side.",
        "Compliance requires the full change history — admin edits write an immutable record with before and after snapshots.",
        "where do we see who changed a setting?",
        "can audit records be edited or deleted?",
        "audit trail contents",
        "how is the change history reconstructed?",
    ],
    &[
        "Quarterly, we restore a random nightly backup into a sandbox and diff it against the source to prove the backups are real.",
        "The restore drill picks one snapshot at random each quarter, stands it up in a sandbox, and compares row counts and checksums.",
        "Backups are verified by doing: a random quarterly restore must match the live database before we trust the rotation.",
        "how do we know the backups actually work?",
        "what proves a restore would succeed?",
        "backup verification process",
        "when was the last restore test?",
    ],
    &[
        "The API tiers size their database pools at four connections per instance because Postgres caps total connections at two hundred.",
        "Pool math: 4 connections × 40 instances ≈ 160, leaving headroom under the server's 200-connection ceiling.",
        "We deliberately keep pools small — four per pod — so a fleet-wide deploy can never exhaust the database.",
        "how many database connections can each instance open?",
        "why can't I raise the pool size?",
        "connection limit planning",
        "what happens to pools during a rolling deploy?",
    ],
    &[
        "Slow-request tracing turns itself off after ten minutes of sustained overhead so the profiler never becomes the outage.",
        "The tracer has a self-imposed ceiling: past ten minutes of heavy overhead it exits, leaving the request path clean.",
        "Observability rule: diagnostics must not damage production — the profiler auto-disables once its cost exceeds a short window.",
        "why did the slow-request trace disappear mid-incident?",
        "can the profiler make things slower?",
        "tracing overhead rules",
        "does diagnostics ever turn itself off?",
    ],
    &[
        "Deleting a workspace archives first and purges after thirty days, so mass deletes are recoverable for a month.",
        "Workspace deletion is two-phase — an archive stage the user can undo, then an irreversible purge at day thirty.",
        "The trash window for workspaces is thirty days; after that the compaction job reclaims the storage for real.",
        "can we undo deleting a workspace?",
        "when does a deleted workspace really disappear?",
        "workspace deletion rules",
        "is deleted data recoverable?",
    ],
    &[
        "Every table partition switch happens behind a view rename so long-running readers finish against the old partition.",
        "Partition swaps are atomic from readers' perspective: the view flips, in-flight queries complete on the old data.",
        "Hot partition swaps work because the view indirection lets old readers drain before the old partition unmounts.",
        "do in-flight queries survive a partition swap?",
        "how are partitions replaced without downtime?",
        "partition swap mechanics",
        "what happens to long queries during the swap?",
    ],
    &[
        "The metrics pipeline clamps every counter at its last known good value on restart so crashes cannot zero the dashboards.",
        "A restarted scraper resumes from the last reported value instead of starting from zero, so gaps do not look like outages.",
        "Counter continuity rule: restarts restore the previous value, because zeroed counters once caused a false outage page.",
        "why didn't the dashboard drop to zero during the restart?",
        "how do counters survive a process restart?",
        "counter continuity rules",
        "did the service lose data when it restarted?",
    ],
];
