//! Distillation teacher for the semantic-embedder trainer.
//!
//! The seven failed retrain iterations proved that a from-scratch metric
//! loss cannot teach a 30K-parameter student associative similarity on
//! unseen topics — the missing ingredient is semantic KNOWLEDGE.  This
//! module supplies it offline, with no network and no keys:
//!
//! 1. harvest a large text corpus from this repository (sources, docs,
//!    plans — the project's own domain language);
//! 2. build a PPMI (positive pointwise mutual information) matrix over a
//!    ±4-token window — words that co-occur across the corpus are related;
//! 3. factorize it with randomized SVD into 64-dimensional word vectors
//!    (LSA-style), so the denoised geometry carries real associative
//!    structure ("settings" ↔ "config", "sign in" ↔ "login", …);
//! 4. embed each training text as its idf-weighted word-vector mean — the
//!    teacher vector the student regresses toward.
//!
//! An API teacher can replace steps 1–3 without touching the trainer:
//! `SOFUU_EMB_TEACHER=cache` reads `/tmp/sofuu_teacher_cache.jsonl` with one
//! JSON object per line, `{"text":"…","embedding":[64 floats]}` (or
//! `"vec":[…]}`), generated by any embeddings API.  The student only ever
//! consumes this cache — the shipped runtime stays teacher-free either way.

use std::collections::{HashMap, HashSet};
use std::path::Path;

use crate::train::Rng;

pub const TEACHER_DIM: usize = 64;
pub const CACHE_PATH: &str = "/tmp/sofuu_teacher_cache.jsonl";
const VOCAB_MAX: usize = 8_192;
const CORPUS_CAP_BYTES: usize = 12 * 1024 * 1024;
const WINDOW: usize = 4;

pub struct Teacher {
    /// vocab index → word (for diagnostics)
    words: Vec<String>,
    /// word → vocab index
    index: HashMap<String, u32>,
    /// idf per vocab entry
    idf: Vec<f32>,
    /// word vectors, row-major vocab × TEACHER_DIM
    vecs: Vec<f32>,
    /// cache fallback: exact text → vector (API teacher path)
    cache: HashMap<String, [f32; TEACHER_DIM]>,
    pub hits: usize,
    pub misses: usize,
}

impl Teacher {
    /// Embed one text as the idf-weighted mean of its known word vectors,
    /// L2-normalized.  Empty output (all words unknown) yields `None` and
    /// the trainer falls back to the per-family sparse code.
    pub fn embed(&mut self, text: &str) -> Option<[f32; TEACHER_DIM]> {
        if let Some(v) = self.cache.get(text) {
            self.hits += 1;
            return Some(*v);
        }
        let mut out = [0.0f32; TEACHER_DIM];
        let mut used = 0usize;
        for tok in tokenize(text) {
            if let Some(&i) = self.index.get(&tok) {
                let w = self.idf[i as usize];
                let row = i as usize * TEACHER_DIM;
                for (o, v) in out.iter_mut().zip(&self.vecs[row..row + TEACHER_DIM]) {
                    *o += w * v;
                }
                used += 1;
            }
        }
        let n = (out.iter().map(|v| v * v).sum::<f32>()).sqrt();
        if used == 0 || !n.is_finite() || n <= 1e-9 {
            self.misses += 1;
            return None;
        }
        for v in &mut out {
            *v /= n;
        }
        self.hits += 1;
        Some(out)
    }

    pub fn vocab_size(&self) -> usize {
        self.words.len()
    }

    /// Nearest neighbours of a word in teacher space — diagnostics for
    /// judging whether the geometry is actually associative.
    pub fn neighbors(&self, word: &str, n: usize) -> Vec<(String, f32)> {
        let Some(&i) = self.index.get(word) else {
            return Vec::new();
        };
        let row = i as usize * TEACHER_DIM;
        let mut scores: Vec<(usize, f32)> = (0..self.words.len())
            .map(|j| {
                let r = j * TEACHER_DIM;
                let dot: f32 = self.vecs[row..row + TEACHER_DIM]
                    .iter()
                    .zip(&self.vecs[r..r + TEACHER_DIM])
                    .map(|(a, b)| a * b)
                    .sum();
                (j, dot)
            })
            .collect();
        scores.sort_by(|a, b| b.1.partial_cmp(&a.1).unwrap());
        scores
            .into_iter()
            .filter(|(j, _)| *j != i as usize)
            .take(n)
            .map(|(j, s)| (self.words[j].clone(), s))
            .collect()
    }
}

// ── tokenization + corpus harvest ───────────────────────────────────────

fn tokenize(text: &str) -> Vec<String> {
    let mut out = Vec::new();
    let mut cur = String::new();
    for c in text.chars() {
        if c.is_ascii_alphanumeric() || c == '_' {
            cur.extend(c.to_lowercase());
        } else if !cur.is_empty() {
            if cur.len() >= 2 && cur.len() <= 24 {
                out.push(std::mem::take(&mut cur));
            } else {
                cur.clear();
            }
        }
    }
    if cur.len() >= 2 && cur.len() <= 24 {
        out.push(cur);
    }
    out
}

const SKIP_DIRS: [&str; 7] = [
    "target",
    ".git",
    "node_modules",
    ".sofuu",
    ".zcode",
    "dist",
    "coverage",
];

const TEXT_EXT: [&str; 8] = [
    "rs", "js", "jsx", "md", "txt", "json", "toml", "html",
];

fn harvest_repo(root: &Path) -> Vec<String> {
    let mut lines: Vec<String> = Vec::new();
    let mut total = 0usize;
    let mut stack = vec![root.to_path_buf()];
    while let Some(dir) = stack.pop() {
        let Ok(entries) = std::fs::read_dir(&dir) else {
            continue;
        };
        for entry in entries.flatten() {
            let path = entry.path();
            let name = entry.file_name();
            let name = name.to_string_lossy().to_string();
            if path.is_dir() {
                if !SKIP_DIRS.contains(&name.as_str()) && !name.starts_with('.') {
                    stack.push(path);
                }
                continue;
            }
            let ext = path
                .extension()
                .map(|e| e.to_string_lossy().to_string())
                .unwrap_or_default();
            if !TEXT_EXT.contains(&ext.as_str()) {
                continue;
            }
            if let Ok(meta) = entry.metadata() {
                if meta.len() > 1_000_000 {
                    continue;
                }
            }
            if let Ok(text) = std::fs::read_to_string(&path) {
                for line in text.lines() {
                    let line = line.trim();
                    if line.len() < 24 {
                        continue;
                    }
                    total += line.len();
                    if total > CORPUS_CAP_BYTES {
                        return lines;
                    }
                    lines.push(line.to_string());
                }
            }
        }
    }
    lines
}

// ── PPMI + randomized SVD ───────────────────────────────────────────────

struct Counted {
    tokens: Vec<u32>,
    words: Vec<String>,
    index: HashMap<String, u32>,
    df: Vec<u32>,
    n_docs: usize,
}

fn count_corpus(texts: &[String]) -> Counted {
    let mut cf: HashMap<String, u32> = HashMap::new();
    let mut docs: Vec<Vec<String>> = Vec::with_capacity(texts.len());
    for t in texts {
        let toks = tokenize(t);
        for tok in &toks {
            *cf.entry(tok.clone()).or_insert(0) += 1;
        }
        docs.push(toks);
    }
    let mut words: Vec<(String, u32)> = cf
        .into_iter()
        .filter(|(w, c)| *c >= 2 && w.len() >= 2)
        .collect();
    words.sort_by(|a, b| b.1.cmp(&a.1).then(a.0.cmp(&b.0)));
    words.truncate(VOCAB_MAX);
    let index: HashMap<String, u32> = words
        .iter()
        .enumerate()
        .map(|(i, (w, _))| (w.clone(), i as u32))
        .collect();
    let words: Vec<String> = words.into_iter().map(|(w, _)| w).collect();
    let mut df = vec![0u32; words.len()];
    let mut tokens = Vec::new();
    for d in &docs {
        let mut seen = HashSet::new();
        let mut encoded = Vec::with_capacity(d.len());
        for tok in d {
            if let Some(&i) = index.get(tok) {
                encoded.push(i);
                if seen.insert(i) {
                    df[i as usize] += 1;
                }
            }
        }
        tokens.extend(encoded);
    }
    Counted {
        tokens,
        words,
        index,
        df,
        n_docs: docs.len(),
    }
}

/// Randomized SVD of the PPMI matrix, returning `d`-dimensional word
/// vectors (rows of U·Σ^0.5, truncated to the top `d` components).
fn ppmi_svd(
    pairs: &[(u32, u32, f32)],
    vocab: usize,
    d: usize,
    rng: &mut Rng,
) -> Vec<f32> {
    let q = (d + 16).min(vocab); // oversampling
    // random Gaussian test matrix Ω (vocab × q)
    let mut omega = vec![0.0f32; vocab * q];
    for v in &mut omega {
        *v = rng.normal() * 0.35;
    }
    // Y = PPMI × Ω  (vocab × q)
    let mut y = vec![0.0f32; vocab * q];
    for &(i, j, m) in pairs {
        let row = i as usize * q;
        let src = j as usize * q;
        for t in 0..q {
            y[row + t] += m * omega[src + t];
        }
    }
    // orthonormalize Y's columns (modified Gram–Schmidt)
    for c in 0..q {
        for cp in 0..c {
            let mut dot = 0.0f32;
            for i in 0..vocab {
                dot += y[i * q + c] * y[i * q + cp];
            }
            for i in 0..vocab {
                y[i * q + c] -= dot * y[i * q + cp];
            }
        }
        let mut n = 0.0f32;
        for i in 0..vocab {
            n += y[i * q + c] * y[i * q + c];
        }
        let n = n.sqrt().max(1e-9);
        for i in 0..vocab {
            y[i * q + c] /= n;
        }
    }
    // B = Qᵀ · PPMI  (q × vocab)
    let mut b = vec![0.0f32; q * vocab];
    for &(i, j, m) in pairs {
        let src = i as usize * q;
        for t in 0..q {
            b[t * vocab + j as usize] += y[src + t] * m;
        }
    }
    // eigen-decompose B·Bᵀ (q × q, symmetric PSD) via cyclic Jacobi
    let mut bbt = vec![0.0f32; q * q];
    for t in 0..q {
        for tp in 0..q {
            let mut dot = 0.0f32;
            for j in 0..vocab {
                dot += b[t * vocab + j] * b[tp * vocab + j];
            }
            bbt[t * q + tp] = dot;
        }
    }
    let (evals, evecs) = jacobi_eigen(&mut bbt, q);
    // top-d components by eigenvalue
    let mut order: Vec<usize> = (0..q).collect();
    order.sort_by(|&a, &b| evals[b].partial_cmp(&evals[a]).unwrap());
    // word vectors: rows of Q · U_d · Σ_d^0.5
    let mut out = vec![0.0f32; vocab * d];
    for (col, &t) in order.iter().take(d).enumerate() {
        let sigma = evals[t].max(0.0).sqrt();
        if sigma < 1e-6 {
            continue;
        }
        for i in 0..vocab {
            let mut acc = 0.0f32;
        for (tp, evec_row) in (0..q).enumerate() {
            acc += y[i * q + evec_row] * evecs[evec_row * q + t];
        }
            out[i * d + col] = acc * sigma;
        }
    }
    // normalize rows so teacher cosine is well-defined
    for i in 0..vocab {
        let row = &mut out[i * d..(i + 1) * d];
        let n = row.iter().map(|v| v * v).sum::<f32>().sqrt();
        if n > 1e-9 {
            for v in row.iter_mut() {
                *v /= n;
            }
        }
    }
    out
}

/// Cyclic Jacobi eigen-decomposition of a symmetric matrix (row-major n×n).
/// Returns (eigenvalues, eigenvectors as columns).
fn jacobi_eigen(a: &mut [f32], n: usize) -> (Vec<f32>, Vec<f32>) {
    let mut v = vec![0.0f32; n * n];
    for i in 0..n {
        v[i * n + i] = 1.0;
    }
    for _sweep in 0..16 {
        let mut off = 0.0f32;
        for i in 0..n {
            for j in (i + 1)..n {
                off += a[i * n + j] * a[i * n + j];
            }
        }
        if off < 1e-10 {
            break;
        }
        for p in 0..n {
            for q in (p + 1)..n {
                let apq = a[p * n + q];
                if apq.abs() < 1e-12 {
                    continue;
                }
                let theta = (a[q * n + q] - a[p * n + p]) / (2.0 * apq);
                let t = theta.signum() / (theta.abs() + (theta * theta + 1.0).sqrt());
                let c = 1.0 / (t * t + 1.0).sqrt();
                let s = t * c;
                for k in 0..n {
                    let akp = a[k * n + p];
                    let akq = a[k * n + q];
                    a[k * n + p] = c * akp - s * akq;
                    a[k * n + q] = s * akp + c * akq;
                }
                for k in 0..n {
                    let apk = a[p * n + k];
                    let aqk = a[q * n + k];
                    a[p * n + k] = c * apk - s * aqk;
                    a[q * n + k] = s * apk + c * aqk;
                }
                for k in 0..n {
                    let vkp = v[k * n + p];
                    let vkq = v[k * n + q];
                    v[k * n + p] = c * vkp - s * vkq;
                    v[k * n + q] = s * vkp + c * vkq;
                }
            }
        }
    }
    let evals = (0..n).map(|i| a[i * n + i]).collect();
    (evals, v)
}

// ── cache I/O ───────────────────────────────────────────────────────────

fn parse_cache_line(line: &str) -> Option<(String, [f32; TEACHER_DIM])> {
    // hand-rolled parse of {"text"|"t": "...", "embedding"|"vec": [..]}
    let text = between(line, "\"text\"", "\"t\"")?;
    let arr = between(line, "\"embedding\"", "\"vec\"")?;
    let arr = arr.trim().trim_start_matches('[').trim_end_matches(']');
    let mut out = [0.0f32; TEACHER_DIM];
    for (i, part) in arr.split(',').enumerate() {
        if i >= TEACHER_DIM {
            break;
        }
        out[i] = part.trim().parse().ok()?;
    }
    Some((text, out))
}

fn between<'a>(line: &'a str, key_a: &str, key_b: &str) -> Option<String> {
    for key in [key_a, key_b] {
        if let Some(pos) = line.find(key) {
            let rest = &line[pos + key.len()..];
            let colon = rest.find(':')?;
            let rest = rest[colon + 1..].trim_start();
            if let Some(rest) = rest.strip_prefix('"') {
                if let Some(end) = rest.find('"') {
                    return Some(rest[..end].to_string());
                }
            } else if let Some(end) = rest.find(|c| c == ',' || c == '}') {
                return Some(rest[..end].trim().trim_matches('"').to_string());
            }
        }
    }
    None
}

// ── construction ────────────────────────────────────────────────────────

/// Build the local teacher: harvest the repo + the trainer's own corpus,
/// count, PPMI, randomized SVD.  Deterministic for a fixed seed.
pub fn build_local(extra_texts: &[String], seed: u64) -> Teacher {
    println!(
        "teacher: harvesting repository corpus (cap {} MB)…",
        CORPUS_CAP_BYTES / (1024 * 1024)
    );
    let manifest = Path::new(env!("CARGO_MANIFEST_DIR"));
    let root = manifest
        .parent()
        .and_then(|p| p.parent())
        .unwrap_or(manifest);
    let mut texts = harvest_repo(root);
    texts.extend(extra_texts.iter().cloned());
    println!(
        "  corpus: {} documents / {:.1} MB",
        texts.len(),
        texts.iter().map(|t| t.len()).sum::<usize>() as f64 / 1e6
    );
    let counted = count_corpus(&texts);
    println!(
        "  tokens {} across {} docs; vocab {}",
        counted.tokens.len(),
        counted.n_docs,
        counted.words.len()
    );

    let vocab = counted.words.len();
    let mut cf = vec![0u64; vocab];
    for &t in &counted.tokens {
        cf[t as usize] += 1;
    }
    let total_tokens: f64 = cf.iter().sum::<u64>() as f64;
    // context distribution with 0.75 smoothing (standard PPMI practice)
    let total_context: f64 = cf.iter().map(|c| (*c as f64).powf(0.75)).sum();

    println!("  counting co-occurrence (window ±{})…", WINDOW);
    let mut pairs: Vec<(u32, u32, f32)> = Vec::new();
    {
        // sort-based pair counting: collect (a,b) with a<b, sort, run-length
        let mut raw: Vec<u64> = Vec::with_capacity(counted.tokens.len() * WINDOW * 2);
        for (pos, &t) in counted.tokens.iter().enumerate() {
            let w = WINDOW.min(pos.min(counted.tokens.len() - 1 - pos));
            for d in 1..=w {
                let u = counted.tokens[pos + d];
                let (a, b) = if t < u { (t, u) } else { (u, t) };
                raw.push(((a as u64) << 32) | b as u64);
            }
        }
        raw.sort_unstable();
        let n_pairs = raw.len() as f64;
        let mut i = 0usize;
        while i < raw.len() {
            let mut j = i + 1;
            while j < raw.len() && raw[j] == raw[i] {
                j += 1;
            }
            let count = (j - i) as f64;
            let a = (raw[i] >> 32) as usize;
            let b = (raw[i] & 0xFFFF_FFFF) as usize;
            let p_ij = count / n_pairs;
            let p_i = cf[a] as f64 / total_tokens;
            let p_cj = (cf[b] as f64).powf(0.75) / total_context;
            let ppmi = (p_ij / (p_i * p_cj)).log2().max(0.0);
            if ppmi > 0.0 {
                pairs.push((a as u32, b as u32, ppmi as f32));
            }
            i = j;
        }
    }
    println!("  PPMI pairs with signal: {}", pairs.len());

    let mut rng = Rng(seed ^ 0x7EAC_7EA1_1109);
    let vecs = ppmi_svd(&pairs, vocab, TEACHER_DIM, &mut rng);
    let idf: Vec<f32> = counted
        .df
        .iter()
        .map(|&d| {
            ((counted.n_docs.max(1) as f32 + 1.0) / (d as f32 + 1.0))
                .ln()
                .max(0.0)
        })
        .collect();
    println!("teacher ready: {} word vectors, {}-dim", vocab, TEACHER_DIM);
    Teacher {
        words: counted.words,
        index: counted.index,
        idf,
        vecs,
        cache: HashMap::new(),
        hits: 0,
        misses: 0,
    }
}

/// Load an API-generated cache (`{"text":…,"embedding":[…]}` JSONL).
/// Returns a teacher whose `embed` hits the cache first and otherwise
/// returns None (the trainer falls back to the family code).
pub fn from_cache() -> Option<Teacher> {
    let text = std::fs::read_to_string(CACHE_PATH).ok()?;
    let mut cache = HashMap::new();
    for line in text.lines() {
        if let Some((t, v)) = parse_cache_line(line) {
            cache.insert(t, v);
        }
    }
    if cache.is_empty() {
        return None;
    }
    println!(
        "teacher: loaded {} cached vectors from {}",
        cache.len(),
        CACHE_PATH
    );
    Some(Teacher {
        words: Vec::new(),
        index: HashMap::new(),
        idf: Vec::new(),
        vecs: Vec::new(),
        cache,
        hits: 0,
        misses: 0,
    })
}
